BoxLayout:
    orientation: "vertical"

    MDBottomNavigation:
        MDBottomNavigationItem:
            name: "screen1"
            icon: "resistor"

            Markings:

        MDBottomNavigationItem:
            name: "screen2"
            icon: "calculator"

            Calculations:

        MDBottomNavigationItem:
            name: "screen3"
            icon: "help"

            AboutScreen: