<MDLabelCenter@MDLabel>:
    text_size: self.size
    halign: "center"
    valign: "center"

<MDScreenTitle@MDLabel>:
    adaptive_height: True
    halign: "center"
    text_size: self.size

<MDFlatButtonTransLeft@MDFlatButton>:
    text_size: self.size
    halign: "center"
    valign: "center"
    pos_hint: {"left": 1, "center_y": .5}

<RippleCard@MDCard>:
    ripple_behavior: True
    padding: 30, 10, 10, 10